name: Trigger A's Workflow

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  post_request:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request with curl
        run: |
          curl -X POST \
            ${{ secrets.WEBHOOK_URL }}